fix: Handle column name conflict with reserved sql
* Error:
```
KeyError: ('CREATE TABLE IF NOT EXISTS "app_db"."sys_config" (\nid DECIMAL(20,0),\ngroup VARCHAR(512),....
.....
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '42601', 'M': 'syntax error at or near "group"', 'P': '84', 'F': '/home/ec2-user/padb/src/pg/src/backend/parser/parser_scan.l', 'L': '714', 'R': 'yyerror'}
```
Reference here: https://docs.aws.amazon.com/redshift/latest/dg/r_pg_keywords.html